name: Kafka Producer

on:
  workflow_dispatch:

jobs:
  produce:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r producer/requirements.txt

      - name: Send Kafka event
        env:
          KAFKA_HOST: ${{ secrets.KAFKA_HOST }}
          KAFKA_PORT: ${{ secrets.KAFKA_PORT }}
          KAFKA_USERNAME: ${{ secrets.KAFKA_USERNAME }}
          KAFKA_PASSWORD: ${{ secrets.KAFKA_PASSWORD }}
        run: |
          python producer/producer.py
